### ISSUE TITLE
Create challenges within Channel 

### ISSUE THREAD

**Issue by nadrojisk** [chharles/CTF-Bot#4]
We should have the option to be able to create ctf challenges within the ctf channel / server. 

Probably should be able to specify `name, points, category`

**Comment by chharles** [comment]
That's a great idea. I added the feature to the most recent version of the development branch.
The command to use the feature is '!add_challenge <ctf_name> <challenge> <topic> <points>'. After issuing the command, a new channel with the specified topic and challenge name will be added to the server.
