### ISSUE TITLE
Ability to work on / leave a challenge

### ISSUE THREAD

**Issue by nadrojisk** [chharles/CTF-Bot#6]
Have the ability to tell the bot that you are working on a challenge. This allows other users to see who's working on what easily.

**Comment by chharles** [comment]
I added the ability to add and remove users to specific **active** challenges. Currently the use of this feature is restricted to admins or the top level users. 
To add users to a challenge use the !work_on command. And to remove users from active challenges use the !stop_working_on challenge.
