### ISSUE TITLE
Add command to print CTF status

### ISSUE THREAD

**Issue by nadrojisk** [chharles/CTF-Bot#7]
Print time left in CTF

Challenges being currently worked on

Challenge that are solved, and who solved them

**Comment by chharles** [comment]
Great ideas! 
I have added the ability to print the time left in an ongoing CTF  under the 'ctf_details' command. 
The 'active_challenges' command will print all of the challenges that are being worked on, as well as the ones that are solved, who solved them and who is working on what. In addition, each active challenge will show their point value.
